(function(context){
  context.packageme = {
    modules: [],
    cache: [],
    register: function(modulePath, moduleBuilder) {
      this.modules[modulePath] = moduleBuilder;
    },
    require: function(modulePath, startPoint) {
      if(!startPoint)
        startPoint = "/";
      
      // build full path to the required Module based on starterPoint
      if(modulePath.indexOf("./") == 0 || modulePath.indexOf("../") == 0)
        modulePath = startPoint+modulePath;
     
      // normalize full path
      modulePath = this.normalizePath(modulePath);
      
      // try getting module at given path
      var moduleBuilder = this.modules[modulePath] || 
                          this.modules[modulePath+"/index"] || 
                          this.modules[startPoint+"node_modules/"+modulePath] || 
                          this.modules[startPoint+"node_modules/"+modulePath+"/index"] || 
                          this.modules["/node_modules/"+modulePath];

      if(moduleBuilder) {
        return cache[startPoint+modulePath] || cache[startPoint+modulePath] = moduleBuilder();
      }
      else
        throw new Error("module at path '"+modulePath+"' was not found");
    },
    normalizePath: function(path) {
      var isAbsolute = path.charAt(0) === '/',
        trailingSlash = path.slice(-1) === '/';

      // Normalize the path
      path = this.normalizeArray(path.split('/').filter(function(p) {
        return !!p;
      }), !isAbsolute).join('/');

      if (!path && !isAbsolute) {
        path = '.';
      }
      if (path && trailingSlash) {
        path += '/';
      }

      return (isAbsolute ? '/' : '') + path;
    },
    normalizeArray: function(parts, allowAboveRoot) {
      // if the path tries to go above the root, `up` ends up > 0
      var up = 0;
      for (var i = parts.length - 1; i >= 0; i--) {
        var last = parts[i];
        if (last == '.') {
          parts.splice(i, 1);
        } else if (last === '..') {
          parts.splice(i, 1);
          up++;
        } else if (up) {
          parts.splice(i, 1);
          up--;
        }
      }

      // if the path is allowed to go above the root, restore leading ..s
      if (allowAboveRoot) {
        for (; up--; up) {
          parts.unshift('..');
        }
      }

      return parts;
    }
  }
})(window);
(function(){
  var require = function(path){
    return window.packageme.require(path, require.path);
  };
  require.path = "sample-package-data/";
  var exports = {};
  var module = {exports: exports};
  window.packageme.register("sample-package-data/index", function(){
    var siblingModule = require("./module");
    var node_module = require("module");
    module.exports = function() {
      return siblingModule.test()+"{code}"+node_module();
    }
    return module.exports;
  });
})();
(function(){
  var require = function(path){
    return window.packageme.require(path, require.path);
  };
  require.path = "sample-package-data/node_modules/module/";
  var exports = {};
  var module = {exports: exports};
  window.packageme.register("sample-package-data/node_modules/module/index", function(){
    
    module.exports = function() {
      var m = require("fancyModule");
      return "main"+m();
    }
    return module.exports;
  });
})();
(function(){
  var require = function(path){
    return window.packageme.require(path, require.path);
  };
  require.path = "sample-package-data/node_modules/module/node_modules/fancyModule/";
  var exports = {};
  var module = {exports: exports};
  window.packageme.register("sample-package-data/node_modules/module/node_modules/fancyModule/index", function(){
    module.exports = function(){
      return "fancyModule";
    }
    return module.exports;
  });
})();

// Generated by CoffeeScript 1.3.1
(function() {
  var f;

  (f = function() {
    var exports, module, require;
    require = function(path) {
      return window.packageme.require(path, require.path);
    };
    require.path = "sample-package-data/module/";
    exports = {};
    module = {
      exports: exports
    };
    return window.packageme.register("sample-package-data/module/index", function() {
      exports.test = function() {
        return "Hello";
      };
      return module.exports;
    });
  })();

  (f = function() {
    var exports, module, require;
    require = function(path) {
      return window.packageme.require(path, require.path);
    };
    require.path = "sample-package-data/module/";
    exports = {};
    module = {
      exports: exports
    };
    return window.packageme.register("sample-package-data/module/innerModule", function() {
      var InnerModule;
      module.exports = InnerModule = (function() {

        InnerModule.name = 'InnerModule';

        function InnerModule() {
          this.value = "helloworld";
        }

        return InnerModule;

      })();
      return module.exports;
    });
  })();

  (f = function() {
    var exports, module, require;
    require = function(path) {
      return window.packageme.require(path, require.path);
    };
    require.path = "sample-package-data/";
    exports = {};
    module = {
      exports: exports
    };
    return window.packageme.register("sample-package-data/test", function() {
      exports.testFunc = function(code) {
        return {
          code: code
        };
      };
      return module.exports;
    });
  })();

}).call(this);

window.packageme.require('sample-package-data/index.js');
